version: 0.2

cache:
  paths:
    - 'pip'

phases:
  install:
    runtime-versions:
      python: 3.5
      python: 3.6
      python: 3.7
      python: 3.8

  pre_build:
    commands:
      - pip install flake8
      - pip install -r requirements.txt
  
  build:
    commands:
      - flake8
      - python -W always setup.py -q test

  post_build:
    commands:
      - echo Build successful.